name: hodge-comp-edge-gp

dependencies:
  - pip:
      - gpytorch==1.11
      - gudhi==3.8.0
      - keopscore==2.1.2
      - matplotlib==3.8.0
      - networkx==3.0
      - numba==0.58.0
      - numpy==1.25.2
      - pandas==2.1.0
      - pykeops==2.1.2
      - scikit-learn==1.3.0
      - scipy==1.11.2
      - seaborn==0.12.2
      - torch==2.2.0


